import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const name = "raghav sharma";
  const navItems = ["Work", "About", "Contact"];

  return (
    <html lang="en">
      <body className="min-h-screen bg-black text-white">
        <Navbar name={name} navItems={navItems} />
        {children}
      </body>
    </html>
  );
}
